USE TABEL1
SET TALK OFF
DO WHILE.T.
CLEAR
?'**Program'         
TEXT
FUNCTII OFERITE:
1-ADD
2-AFISARE
3-MODIFICARE INREGISTRARE _NUME DE LA TASTA
4-STERGERE_CODA DE LA TASTA
5-REVALIDARE_NR.INREG DE LA TASTA
6-ELIMINARE MARCATE
7-AFISARE VECHIME>3
0-END
ENDTEXT
WAIT TO R
IF.NOT.R$'12345670'
return
ENDIF


DO CASE
CASE R='1'
USE TABEL1
VNUME = TRIM(ACCEPT('Nume:'))
VCODA = VAL(ACCEPT('CODA'))
VDATA = CTOD(ACCEPT('Data'))
VSALAR = VAL(ACCEPT('Salar:'))
VVECHIME = VAL(ACCEPT('Vechime:'))
APPEND BLANK
REPL CODA WITH VCODA,NUME WITH VNUME,DATA_ANG WITH VDATA, SALAR WITH VSALAR
REPL VECHIME WITH VVECHIME


CASE R='2'
USE TABEL1
DISP ALL
WAIT 

CASE R='3'
USE TABEL1
VNUME = TRIM(ACCEPT('Numele studentului:'))
LOCATE FOR NUME = VNUME
IF EOF() 
	?'Studentul cu numele' + VNUME + 'nu exista'
   WAIT
   LOOP
ENDIF
EDIT

CASE R='4'
USE TABEL1 
GO TOP
N=VAL(ACCEPT('NR.inregistrare pentru stergere:')) 
SCAN FOR CODA=N
DELETE RECORD N
IF EOF()
EXIT()
ENDIF
ENDSCAN

CASE R='5'
USE TABEL1
N=VAL(ACCEPT('Nr.articol ce se revalideaza:'))
RECALL RECORD N


CASE R='6'
USE TABEL1
PACK
WAIT
?'Noul fisier este:'
LIST

CASE R='7'
USE TABEL1
GO TOP
DO WHILE.NOT.EOF()
IF VECHIME>3
DISP
ENDIF
SKIP
ENDDO


CASE R='0'
USE 
RETURN

ENDCASE
ENDDO

